/*--------------------------------------------------------------------------*/
/*-------------------------- File complete.C -------------------------------*/
/*--------------------------------------------------------------------------*/
/*--                                                                      --*/
/*-- Generator of random complete networks. Reads the following           --*/
/*-- parameters from the standard input:                                  --*/
/*--  - number of nodes                                                   --*/
/*--  - average number of copies of each arc: 0 means that only one copy  --*/
/*--    of each arc (in one of the two orientations) is constructed       --*/
/*--  - max cost range                                                    --*/
/*--  - min cost range                                                    --*/
/*--  - max capacity range                                                --*/
/*--  - min capacity range                                                --*/
/*--  - average deficit of each source/sink node                          --*/
/*--  - total flow produced in the graph                                  --*/
/*--  - seed for the random number generator                              --*/
/*--                                                                      --*/
/*-- Cost and capacities are uniform within their ranges; sources and     --*/
/*-- sinks are uniformly scattered in the graph. No feasibility check is  --*/
/*-- done (instances can be unfeasible). The output is in DIMACS format.  --*/
/*--                                                                      --*/
/*--                            VERSION 0.11                              --*/
/*--                           12 - 05 - 2004                             --*/
/*--                                                                      --*/
/*--                 Original Idea and Implementation by:                 --*/
/*--                                                                      --*/
/*--                          Antonio Frangioni                           --*/
/*--                                                                      --*/
/*--                       Operations Research Group                      --*/
/*--                      Dipartimento di Informatica                     --*/
/*--                         Universita' di Pisa                          --*/
/*--                                                                      --*/
/*--                           Claudio Gentile                            --*/
/*--                                                                      --*/
/*--            Istituto di Analisi di Sistemi ed Informatica             --*/
/*--                 Consiglio Nazionale delle Ricerche                   --*/
/*--                        Viale Manzoni, 30 Roma                        --*/
/*--                                                                      --*/
/*--------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------*/

/*--------------------------------------------------------------------------*/
/*------------------------------ INCLUDES ----------------------------------*/
/*--------------------------------------------------------------------------*/

#include <iostream>
#include <fstream>

#include <stdlib.h>

using namespace std;

/*--------------------------------------------------------------------------*/

int main( int argc , char **argv )
{
 // reading command line parameters - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

 if( argc < 2 )
 {
  cerr << "Usage: " << argv[ 0 ] << " <output file>" << endl;
  return( -1 );
  }

 // opening input stream- - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

 ofstream oFile( argv[ 1 ] );
 if( ! oFile )
 {
  cerr << "ERROR: opening output file " << argv[ 1 ] << endl;
  return( -1 );
  }

 // reading parameters- - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

 int n;
 cin >> n;

 int avgp;
 cin >> avgp;

 int mxcst;
 cin >> mxcst;

 int mncst;
 cin >> mncst;

 int mxcap;
 cin >> mxcap;

 int mncap;
 cin >> mncap;

 int avgdfct;
 cin >> avgdfct;

 int totdfct;
 cin >> totdfct;

 long int seed;
 cin >> seed;

 srand48( seed );

 // writing preamble- - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

 oFile << "c generated by the " << argv[ 0 ] << " generator" << endl
       << "c n = " << n << endl
       << "c average parallel = " << avgp << endl
       << "c max/min cost = " << mxcst << "/" << mncst << endl
       << "c max/min capacity = " << mxcap << "/" << mncap << endl
       << "c average deficit = " << avgdfct << endl
       << "c total deficit = " << totdfct << endl
       << "c seed = " << seed << endl
       << "p min " << n << " ";

 // creating arcs - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

 int maxn = n * ( n - 1 ) * 2 * ( 1 + avgp );
 
 int *Sn = new int[ maxn ];
 int *En = new int[ maxn ];
 int *C  = new int[ maxn ];
 int *U  = new int[ maxn ];

 int m = 0;
 for( int i = 1 ; i <= n ; i++ )
  for( int j = i ; ++j <= n ; )
   for( int h = int( 2 * avgp * drand48() + 1 ) ; h-- ; )
   {
    if( int( 2 * drand48() ) )
    {
     Sn[ m ] = i;
     En[ m ] = j;
     }
    else
    {
     Sn[ m ] = j;
     En[ m ] = i;
     }

    C[ m ]   = mncst + int( drand48() * ( mxcst - mncst ) );
    U[ m++ ] = mncap + int( drand48() * ( mxcap - mncap ) );
    }

 // writing arcs- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

 oFile << m << endl;

 for( int i = 0 ; i < m ; i++ )
   oFile << "a\t" << Sn[ i ] << "\t" << En[ i ] << "\t0\t" << U[ i ] << "\t"
	 << C[ i ] << endl;

 delete[] U;
 delete[] C;
 delete[] En;
 delete[] Sn;

 // creating nodes- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

 int *B = new int[ n ];
 for( int i = 0 ; i < n ; )
  B[ i++ ] = 0;

 for( int tmpdfct = totdfct ; tmpdfct ; )
 {
  int i = int( drand48() * n );
  int Bi = int( drand48() * avgdfct );
  if( Bi > tmpdfct )
   Bi = tmpdfct;

  B[ i ] += Bi;
  tmpdfct -= Bi;
  }

 for( int tmpdfct = totdfct ; tmpdfct ; )
 {
  int i = int( drand48() * n );
  int Bi = int( drand48() * avgdfct );
  if( Bi > tmpdfct )
   Bi = tmpdfct;

  B[ i ] -= Bi;
  tmpdfct -= Bi;
  }

 // writing nodes - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

 for( int i = 0 ; i < n ; i++ )
  if( B[ i ] )
   oFile << "n\t" << i + 1 << "\t" << B[ i ] << endl;

 delete[] B;

 // terminate - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

 return( 0 );

 }  // end( main )

/*--------------------------------------------------------------------------*/
/*----------------------- End File complete.C ------------------------------*/
/*--------------------------------------------------------------------------*/
